import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Cards from "@/components/Cards";
import Section from "@/components/Section";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Cards/>
        <Section/>
        <Footer/>
        </body>
    </html>
  );
}
